
export const SUB_COINT = 'SUB_COINT';
export const ADD_COINT = 'ADD_COINT';
export const SET_HEART = 'SET_HEART';
export const SET_WAVES = 'SET_WAVES';
export const SET_LEVEL = 'SET_LEVEL';

export const SET_COINT_TEXT = 'SET_COINT_TEXT';
export const SET_HEART_TEXT = 'SET_HEART_TEXT';
export const SET_WAVES_TEXT = 'SET_WAVES_TEXT';
export const SET_LEVEL_TEXT = 'SET_LEVEL_TEXT';
export const RESET_GAMELAY_UI = 'RESET_GAMELAY_UI';

export const HIDE_POPUP = 'HIDE_POPUP';
export const SHOW_HOME_SCREEN = 'SHOW_HOME_SCREEN';
export const SHOW_SETTING_POPUP = 'SHOW_SETTING_POPUP';
export const SHOW_GAME_OVER_POPUP = 'SHOW_GAME_OVER_POPUP';
export const SHOW_GAME_WIN_POPUP = 'SHOW_GAME_WIN_POPUP';

export const RESET_GAME = 'RESET_GAME';
export const START_GAME = 'START_GAME';
export const PAUSE_GAME = 'PAUSE_GAME';
export const UN_PAUSE_GAME = 'UN_PAUSE_GAME';

export const SPEED_CHANGE = 'SPEED_CHANGE';
export const CHANGE_VOLUME_SOUND = 'CHANGE_VOLUME_SOUND';
export const CHANGE_VOLUME_MUSIC = 'CHANGE_VOLUME_MUSIC';
export const CHANGE_HAND_SOUND = 'CHANGE_HAND_SOUND';
export const CHANGE_HAND_MUSIC = 'CHANGE_HAND_MUSIC';
export const PLAY_AMMO_SOUND = 'PLAY_SHOOT_SOUND';
export const PLAY_ROCKET_SOUND = 'PLAY_ROCKET_SOUND';
export const PLAY_EXPLOSION_SOUND = 'PLAY_EXPLOSION_SOUND';


